services:

  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    networks:
      - dormant_net

  dormant:
    build:
      context: .
      dockerfile: trade/Dockerfile
    container_name: dormant-container
    ports:
      - 8081:8081
      - 5005:5005
    environment:
      - FACEBOOK_CLIENT_ID=1620430302605224
      - FACEBOOK_CLIENT_SECRET=691f07fa6e37afc0eff68f57908c098a
      - GITHUB_CLIENT_ID=Ov23ctUEXkrwxXa8eO2f
      - GITHUB_CLIENT_SECRET=977ac3096c99b068ac7daf80c62239d666c6cf57
      - GOOGLE_CLIENT_ID=321671510578-g4mdj28njvqj3kamjj128gn85vn7g41u.apps.googleusercontent.com
      - GOOGLE_CLIENT_ID1=321671510578-ndmjd8lhcbifntfobfefj5le7tle8cue.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CLIENT_SECRET1=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
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./data:/trade/data
    networks:
      - dormant_net

  gui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "4173:4173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://dormant-container:8081/api
      - NODE_ENV=development
    networks:
      - dormant_net

networks:
  dormant_net:
    driver: bridge

